# ===============================
# 1. CONEXION A POSTGRESQL
# ===============================
# Cambia 'tu_base_de_datos', 'postgres' y 'tu_contrasena' por tus datos reales
spring.datasource.url=jdbc:postgresql://localhost:5432/devoluciones_db
spring.datasource.username=jlmendoza
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# 2. CONFIGURACION DE JPA / HIBERNATE
# ===============================
# 'update' actualiza el esquema de la BD automaticamente segun tus clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# 3. OPTIMIZACION PARA IMPORTACIONES MASIVAS (BATCHING)
# ===============================
# Agrupa las sentencias SQL en lotes de 50 para no colapsar la red
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ===============================
# 4. LIMITES DE SUBIDA DE ARCHIVOS
# ===============================
# Aumentamos el limite a 50MB para soportar la carga de archivos CSV pesados
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# 5. CONFIGURACION DE SEGURIDAD (JWT)
# ===============================
# La clave secreta debe ser larga para el algoritmo HS256
jwt.secret=EstaEsUnaClaveSecretaMuyLargaYSeguraParaNuestraAppDeSpring2026!
jwt.expiration=86400000